<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NominesV extends \AppBundle\Entity\NominesV implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'idCat', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'nomine1', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'nomine2', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'nomine3', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'domaine', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'annee', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'elu', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'commentaire', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'longcomm', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'photo'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'idCat', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'nomine1', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'nomine2', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'nomine3', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'domaine', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'annee', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'elu', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'commentaire', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'longcomm', '' . "\0" . 'AppBundle\\Entity\\NominesV' . "\0" . 'photo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (NominesV $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCat($idCat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCat', [$idCat]);

        return parent::setIdCat($idCat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCat', []);

        return parent::getIdCat();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomine1($nomine1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomine1', [$nomine1]);

        return parent::setNomine1($nomine1);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomine1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomine1', []);

        return parent::getNomine1();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomine2($nomine2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomine2', [$nomine2]);

        return parent::setNomine2($nomine2);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomine2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomine2', []);

        return parent::getNomine2();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomine3($nomine3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomine3', [$nomine3]);

        return parent::setNomine3($nomine3);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomine3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomine3', []);

        return parent::getNomine3();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomaine($domaine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomaine', [$domaine]);

        return parent::setDomaine($domaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomaine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomaine', []);

        return parent::getDomaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee($annee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', [$annee]);

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', []);

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setElu($elu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setElu', [$elu]);

        return parent::setElu($elu);
    }

    /**
     * {@inheritDoc}
     */
    public function getElu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElu', []);

        return parent::getElu();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire($commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', [$commentaire]);

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', []);

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongcomm($longcomm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongcomm', [$longcomm]);

        return parent::setLongcomm($longcomm);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongcomm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongcomm', []);

        return parent::getLongcomm();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

}
